apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "partycoin"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEBUG
              value: "{{ .Values.app.debug }}"
            - name: SECRET_KEY
              value: "{{ .Values.app.secretKey }}"
            - name: DATABASE_NAME
              value: "{{ .Values.app.database_name }}"
            - name: DATABASE_USER
              value: "{{ .Values.app.database_user }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.app.database_password }}"
            - name: DATABASE_HOST
              value: "{{ .Values.app.database_host }}"
            - name: DATABASE_PORT
              value: "{{ .Values.app.database_port }}"
            - name: DATABASE_CON_MAX_AGE
              value: "600"
            - name: AWS_ACCESS_KEY_ID
              value: "{{ .Values.app.awsAccessKeyID }}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "{{ .Values.app.awsSecretAccessKeyID }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: registry
